#include "Header1.h"
int main()
{
  portk(0x00);
  porta(0xff);
  portc(0xff);
  portb(0xff);
 while(1)
  {
    for(int i=0;i<4;i++)
    {
      highlowf(1<<i);
      highlowa(port_kread);
      if(port_kread!=0)
      {
        highlowc(1<<i);
       if(port_cread==0x01&&port_kread==0x01)
        {
          segb(1);
        }
        if(port_cread==0x01&&port_kread==0x02)
        {
          segb(2);
        }
        if(port_cread==0x01&&port_kread==0x04)
        {
          segb(3);
        }
        if(port_cread==0x02&&port_kread==0x01)
        {
          segb(4);
        }
        if(port_cread==0x02&&port_kread==0x02)
        {
          segb(5);
        }
        if(port_cread==0x02&&port_kread==0x04)
        {
          segb(6);
        }
        if(port_cread==0x04&&port_kread==0x01)
        {
          segb(7);
        }
        if(port_cread==0x04&&port_kread==0x02)
        {
          segb(8);
        }
        if(port_cread==0x04&&port_kread==0x04)
        {
          segb(9);
        }
        if(port_cread==0x08&&port_kread==0x02)
        {
          segb(0);
        }
        delay1(2);
        highlowc(0x00);
      }
    }
  }
}