//All ports and pins are defined and used in other headers.

#define ddrA (*(volatile char*) 0x21)
#define portA_out (*(volatile char*) 0x22)
#define portA_INPUT (*(volatile char*) 0x20)
#define ddrB (*(volatile char*) 0x24)
#define portB_out (*(volatile char*) 0x25)
#define portB_INPUT (*(volatile char*) 0x23)
#define ddrC (*(volatile char*) 0x27)
#define portC_out (*(volatile char*) 0x28)
#define portC_INPUT (*(volatile char*) 0x26)
#define ddrD (*(volatile char*) 0x2A)
#define portD_out (*(volatile char*) 0x2B)
#define portD_INPUT (*(volatile char*) 0x29)
#define ddrE (*(volatile char*) 0x2D)
#define portE_out (*(volatile char*) 0x2E)
#define portE_INPUT (*(volatile char*) 0x2C)
#define ddrF (*(volatile char*) 0x30)
#define portF_out (*(volatile char*) 0x31)
#define portF_INPUT (*(volatile char*) 0x2F)
#define ddrG (*(volatile char*) 0x33)
#define portG_out (*(volatile char*) 0x34)
#define portG_INPUT (*(volatile char*) 0x32)
#define ddrH (*(volatile char*) 0x101)
#define portH_out (*(volatile char*) 0x102)
#define portH_INPUT (*(volatile char*) 0x100)
#define ddrJ (*(volatile char*) 0x104)
#define portJ_out (*(volatile char*) 0x105)
#define portJ_INPUT (*(volatile char*) 0x103)
#define ddrK (*(volatile char*) 0x107)
#define portK_out (*(volatile char*) 0x108)
#define portK_INPUT (*(volatile char*) 0x106)
#define ddrL (*(volatile char*) 0x10A)
#define portL_out (*(volatile char*) 0x10B)
#define portL_INPUT (*(volatile char*) 0x109)
#define high 1
#define low 0